{"timestamp":"2025-07-12T00:26:07.165714","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-12T00:26:07.166566","level":"info","event":"Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-12T00:26:07.227630Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-12T00:26:07.227807Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-12T00:26:07.227892Z","level":"info","event":"Current task name:transform_load_weather_data","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-12T00:26:07.227998Z","level":"info","event":"Dag name:weathermap_api","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-12T00:26:07.264020","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"ImportError","exc_value":"Install s3fs to access S3","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":867,"name":"run"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1159,"name":"_execute_task"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/home/ubuntu/airflow/dags/weather_dag.py","lineno":50,"name":"transform_load_data"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/util/_decorators.py","lineno":333,"name":"wrapper"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/core/generic.py","lineno":3986,"name":"to_csv"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/io/formats/format.py","lineno":1014,"name":"to_csv"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/io/formats/csvs.py","lineno":251,"name":"save"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/io/common.py","lineno":728,"name":"get_handle"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/io/common.py","lineno":430,"name":"_get_filepath_or_buffer"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/fsspec/core.py","lineno":491,"name":"open"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/fsspec/core.py","lineno":295,"name":"open_files"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/fsspec/core.py","lineno":655,"name":"get_fs_token_paths"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/fsspec/core.py","lineno":351,"name":"_un_chain"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/fsspec/registry.py","lineno":259,"name":"get_filesystem_class"}],"is_group":false,"exceptions":[]},{"exc_type":"ModuleNotFoundError","exc_value":"No module named 'botocore.context'","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/fsspec/registry.py","lineno":257,"name":"get_filesystem_class"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/fsspec/registry.py","lineno":292,"name":"_import_class"},{"filename":"/usr/lib/python3.12/importlib/__init__.py","lineno":90,"name":"import_module"},{"filename":"<frozen importlib._bootstrap>","lineno":1387,"name":"_gcd_import"},{"filename":"<frozen importlib._bootstrap>","lineno":1360,"name":"_find_and_load"},{"filename":"<frozen importlib._bootstrap>","lineno":1331,"name":"_find_and_load_unlocked"},{"filename":"<frozen importlib._bootstrap>","lineno":935,"name":"_load_unlocked"},{"filename":"<frozen importlib._bootstrap_external>","lineno":995,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3fs/__init__.py","lineno":1,"name":"<module>"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3fs/core.py","lineno":30,"name":"<module>"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/aiobotocore/session.py","lineno":4,"name":"<module>"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-12T00:26:07.296400Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-12T00:26:07.296540Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-12T00:26:07.296599Z","level":"info","event":"Task:<Task(PythonOperator): transform_load_weather_data>","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-12T00:26:07.296643Z","level":"info","event":"Failure caused by Install s3fs to access S3","chan":"stdout","logger":"task"}
